services:
  # CrowdSec - Open-source & collaborative security IPS
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8080:8080"
      # - "$ZEROTIER_IP_CLOUDSERVER:6060:6060" # Exposing metrics via Zerotier IP
    environment:
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux fulljackz/proxmox"
      GID: "${GID-1000}"
      CUSTOM_HOSTNAME: home-server
      DISABLE_LOCAL_API: "true" # Только после успешной регистрации и проверки удаленного агента ниже.
      # Далее проверьте local_api_credentials.yaml после регистрации cscli lapi (дополнительный компьютер) и проверки компьютера cscli (на основном компьютере).
      AGENT_USERNAME: $CROWDSEC_AGENT_USERNAME 
      AGENT_PASSWORD: $CROWDSEC_AGENT_PASSWORD 
      LOCAL_API_URL: $CROWDSEC_LOCAL_API_URL 
    volumes:
      - $LOGSDIR/cloudserver:/logs/cloudserver:ro
      - /var/log:/var/log:ro
      - $EXTDRIVE/zbox/var/log:/logs/zbox:ro
      - $APPDATADIR/crowdsec/data:/var/lib/crowdsec/data
      - $APPDATADIR/crowdsec/config:/etc/crowdsec